theme: jekyll-theme-hacker 
baseurl: "/101flags"        
url: "https://username.github.io"  
title: Your CTF Writeups
description: Collection of security challenge solutions
show_downloads: false
plugins: [jekyll-feed]